#' Sample generated Stan code with ulam-style arguments
#'
#' Translate the sampling arguments used by rethinking's `ulam()` to
#' [sample_cstan()], returning the same native CmdStanR-style fit. This function
#' accepts Stan source, not an ulam formula, and does not require rethinking,
#' cmdstanr, or rstan.
#'
#' @param model_code Stan program source generated by the caller.
#' @param data Named list of model data.
#' @param chains Number of chains.
#' @param cores Maximum concurrent chains (translated to `parallel_chains`).
#' @param iter Total iterations per chain, including warmup, before thinning.
#' @param warmup Warmup iterations per chain; defaults to `floor(iter / 2)`.
#' @param control Named list containing `adapt_delta` and/or `max_treedepth`.
#'   The acceptance target defaults to 0.95, including for an empty control list.
#' @param start Complete constrained parameter values, one list per chain, or a
#'   function returning a list, optionally accepting `chain_id`. An empty list
#'   uses random initialization. See [sample_cstan()] for initialization limits.
#' @param ... Additional uniquely named [sample_cstan()] arguments, such as
#'   `seed`, `thin`, `refresh`, `save_warmup`, `init_radius`, or `pathfinder_init`.
#'   Arguments must not conflict with translated values. `init` and
#'   `max_treedepth` may be passed here when not supplied through `start` and
#'   `control`, respectively. Warmup draws are saved unless `save_warmup = FALSE`.
#' @return A native `stanli_cstanfit`, as returned by [sample_cstan()].
#' @details Sampling and fit behavior are delegated to [sample_cstan()]; this
#'   entry point only translates and validates arguments. It does not change
#'   that function's defaults. Compiler flags and within-chain threading are
#'   unsupported. Unsupported or conflicting options fail before preparing a
#'   model. Neither iteration counts nor initial values are silently truncated.
#' @md
#' @export
sample_ulam <- function(model_code, data = list(), chains = 1, cores = 1,
                        iter = 1000, warmup = floor(iter / 2),
                        control = list(adapt_delta = 0.95), start = list(), ...) {
  cstan_integer(iter, "iter")
  cstan_integer(warmup, "warmup", 0)
  if (!is.list(control) || (length(control) &&
      (is.null(names(control)) || anyNA(names(control)) || anyDuplicated(names(control)) ||
       any(!names(control) %in% c("adapt_delta", "max_treedepth")))))
    stop("Unsupported Stanli control options", call. = FALSE)
  args <- list(model_code = model_code, data = data, chains = chains, parallel_chains = cores,
               iter_warmup = warmup, iter_sampling = iter - warmup, save_warmup = TRUE,
               adapt_delta = if (is.null(control$adapt_delta)) 0.95 else control$adapt_delta)
  if (!is.null(control$max_treedepth)) args$max_treedepth <- control$max_treedepth
  if (length(start)) args$init <- start
  dots <- list(...)
  if (length(dots) && (is.null(names(dots)) || anyNA(names(dots)) ||
      any(!nzchar(names(dots))) || anyDuplicated(names(dots))))
    stop("Stanli sampling arguments must be uniquely named", call. = FALSE)
  if (any(names(dots) %in% setdiff(names(args), "save_warmup")))
    stop("Conflicting Stanli sampling arguments", call. = FALSE)
  do.call(sample_cstan, utils::modifyList(args, dots, keep.null = TRUE))
}
