cmake_minimum_required(VERSION 3.16)
include("${SOURCE}/cmake/StanliLoopAlignment.cmake")
if(STANLI_ALIGN_LOOPS)
  message(FATAL_ERROR "Loop alignment must remain off by default")
endif()
function(check os arch compiler wasm expected)
  set(CMAKE_SYSTEM_NAME "${os}")
  set(CMAKE_SYSTEM_PROCESSOR "${arch}")
  set(CMAKE_OSX_ARCHITECTURES "${arch}")
  set(CMAKE_CXX_COMPILER_ID "${compiler}")
  set(EMSCRIPTEN "${wasm}")
  stanli_loop_alignment_supported(actual)
  if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "Loop alignment selection failed: ${os}/${arch}/${compiler}/${wasm}")
  endif()
endfunction()
check(Darwin arm64 AppleClang OFF ON)
check(Darwin x86_64 AppleClang OFF OFF)
check(Darwin "arm64;x86_64" AppleClang OFF OFF)
check(Darwin "x86_64;arm64" AppleClang OFF OFF)
check(Darwin arm64 Clang OFF OFF)
check(Linux aarch64 Clang OFF OFF)
check(Linux x86_64 GNU OFF OFF)
check(Windows AMD64 GNU OFF OFF)
check(Emscripten wasm32 Clang ON OFF)
check(Darwin arm64 AppleClang ON OFF)
set(STANLI_SANITIZE address)
check(Darwin arm64 AppleClang OFF OFF)
unset(STANLI_SANITIZE)
set(CMAKE_CXX_FLAGS "-fsanitize=thread")
check(Darwin arm64 AppleClang OFF OFF)
unset(CMAKE_CXX_FLAGS)
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -flto=thin")
check(Darwin arm64 AppleClang OFF OFF)
unset(CMAKE_CXX_FLAGS_RELEASE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
check(Darwin arm64 AppleClang OFF OFF)
unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE)
# Disabled means no target access or compiler check, including unsupported hosts.
set(CMAKE_SYSTEM_NAME Emscripten)
stanli_apply_loop_alignment(nonexistent_target)

# Exercise generated flags and cached ON -> OFF rollback on the real host.
# Selection mocks above are not cross-platform compilation claims.
if(DEFINED BINARY)
  function(configure label build_type enabled expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE}/tests/loop_alignment"
      -B "${BINARY}/${label}" -DSOURCE=${SOURCE} -DCMAKE_BUILD_TYPE=${build_type}
      -DSTANLI_ALIGN_LOOPS=${enabled} ${ARGN}
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Configuration ${label} failed: ${output}\n${error}")
    endif()
    file(READ "${BINARY}/${label}/compile_commands.json" commands)
    if(expected AND NOT commands MATCHES "-falign-loops=32")
      message(FATAL_ERROR "Missing loop alignment in ${label}")
    elseif(NOT expected AND commands MATCHES "-falign-loops")
      message(FATAL_ERROR "Unexpected loop alignment in ${label}")
    endif()
  endfunction()
  configure(default Release OFF OFF)
  configure(unsupported Release OFF OFF -DTEST_UNSUPPORTED=ON)
  configure(unsupported_auto Release AUTO OFF -DTEST_UNSUPPORTED=ON)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE}/tests/loop_alignment"
    -B "${BINARY}/unsupported" -DSOURCE=${SOURCE}
    -DSTANLI_ALIGN_LOOPS=ON -DTEST_UNSUPPORTED=ON
    RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE error)
  if(status EQUAL 0 OR NOT error MATCHES "requires native macOS arm64 Apple Clang")
    message(FATAL_ERROR "Unsupported alignment request was not refused: ${error}")
  endif()
  if(NATIVE_SUPPORTED)
    configure(native_auto Release AUTO ON)
    configure(missing_flag_auto Release AUTO OFF -DSTANLI_HAS_ALIGN_LOOPS_32=FALSE)
    configure(rollback Release ON ON)
    configure(rollback Release OFF OFF)
    configure(relwithdebinfo RelWithDebInfo ON ON)
    configure(debug Debug ON OFF)
    configure(minsizerel MinSizeRel ON OFF)
  endif()
endif()
