cmake_minimum_required(VERSION 3.16)
file(MAKE_DIRECTORY "${BINARY}/export-parser-fixtures")
set(headers "[Ordinal/Name Pointer] Table" "[Ordinal/Name Pointer] Table -- Ordinal Base 1" "Export Table:")
set(rows " [ 0] stanli_build_id" " [ 0] +base[ 1] 0000 stanli_build_id" " 1 0x1000 stanli_build_id")
foreach(i RANGE 0 2)
  list(GET headers ${i} header)
  list(GET rows ${i} row)
  foreach(case valid unexpected missing)
    set(content "${header}\n${row}\n")
    if(case STREQUAL unexpected)
      string(REPLACE stanli_build_id malloc extra "${row}")
      string(APPEND content "${extra}\n")
    elseif(case STREQUAL missing)
      set(content "${header}\n stanli_build_id mentioned but not an export\n")
    endif()
    set(path "${BINARY}/export-parser-fixtures/${i}-${case}.txt")
    file(WRITE "${path}" "${content}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DPLATFORM=Windows -DEXPORT_DUMP=${path}
      -P "${SOURCE}/tests/check_allocator_exports.cmake"
      RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    if(case STREQUAL valid AND NOT result EQUAL 0)
      message(FATAL_ERROR "Valid export format ${i} refused: ${error}")
    elseif(NOT case STREQUAL valid AND result EQUAL 0)
      message(FATAL_ERROR "Invalid export format ${i}/${case} accepted")
    endif()
  endforeach()
endforeach()
