cmake_minimum_required(VERSION 3.16)
if(DEFINED BAD_CASE)
  set(CMAKE_SYSTEM_NAME Emscripten)
  set(CMAKE_SYSTEM_PROCESSOR wasm32)
  set(STANLI_SHARED_ALLOCATOR "${BAD_CASE}" CACHE STRING "" FORCE)
  include("${SOURCE}/cmake/StanliAllocator.cmake")
  message(FATAL_ERROR "Invalid allocator configuration was accepted")
endif()
function(check_default os arch sanitizer expected)
  set(CMAKE_SYSTEM_NAME "${os}")
  set(CMAKE_SYSTEM_PROCESSOR "${arch}")
  set(CMAKE_OSX_ARCHITECTURES "${arch}")
  set(STANLI_SANITIZE "${sanitizer}")
  unset(STANLI_SHARED_ALLOCATOR CACHE)
  include("${SOURCE}/cmake/StanliAllocator.cmake")
  if(NOT "${STANLI_USE_PRIVATE_MIMALLOC}" STREQUAL "${expected}")
    message(FATAL_ERROR "Wrong default allocator: ${os}/${arch}/${sanitizer}")
  endif()
endfunction()
check_default(Linux x86_64 "" ON)
check_default(Linux aarch64 "" ON)
check_default(Linux i686 "" OFF)
check_default(Linux x86_64 address OFF)
check_default(Darwin arm64 "" OFF)
check_default(Darwin x86_64 "" OFF)
check_default(Windows AMD64 "" OFF)
check_default(Windows ARM64 "" OFF)
check_default(Emscripten wasm32 "" OFF)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
check_default(Linux x86_64 "" OFF)
unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION)
function(check mode os arch sanitizer expected)
  set(CMAKE_SYSTEM_NAME "${os}")
  set(CMAKE_SYSTEM_PROCESSOR "${arch}")
  set(CMAKE_OSX_ARCHITECTURES "${arch}")
  set(STANLI_SANITIZE "${sanitizer}")
  set(MINGW ON)
  set(STANLI_SHARED_ALLOCATOR "${mode}" CACHE STRING "" FORCE)
  include("${SOURCE}/cmake/StanliAllocator.cmake")
  if(NOT "${STANLI_USE_PRIVATE_MIMALLOC}" STREQUAL "${expected}")
    message(FATAL_ERROR "Allocator selection failed: ${mode}/${os}/${arch}/${sanitizer}")
  endif()
endfunction()
check(AUTO Darwin arm64 "" ON)
check(MIMALLOC Darwin arm64 "" ON)
check(SYSTEM Darwin arm64 "" OFF)
check(AUTO Darwin x86_64 "" ON)
check(AUTO Darwin "arm64;x86_64" "" ON)
check(AUTO Linux aarch64 "" ON)
check(AUTO Linux x86_64 "" ON)
check(SYSTEM Linux x86_64 "" OFF)
check(SYSTEM Linux aarch64 "" OFF)
check(AUTO Windows AMD64 "" ON)
check(AUTO Windows x86_64 "" ON)
check(AUTO Windows ARM64 "" OFF)
check(AUTO Linux i686 "" OFF)
check(AUTO Emscripten wasm32 "" OFF)
check(AUTO Darwin arm64 address OFF)
set(CMAKE_CXX_FLAGS "-fsanitize=address")
check(AUTO Darwin arm64 "" OFF)
unset(CMAKE_CXX_FLAGS)
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -flto=thin")
check(AUTO Linux x86_64 "" OFF)
unset(CMAKE_CXX_FLAGS_RELEASE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
check(AUTO Windows x86_64 "" OFF)
unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
check(AUTO Linux x86_64 "" OFF)
unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(MINGW OFF)
include("${SOURCE}/cmake/StanliAllocator.cmake")
if(STANLI_USE_PRIVATE_MIMALLOC)
  message(FATAL_ERROR "MSVC must retain SYSTEM")
endif()
foreach(mode TYPO MIMALLOC)
  execute_process(COMMAND "${CMAKE_COMMAND}" -DSOURCE=${SOURCE} -DBAD_CASE=${mode}
    -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
  if(result EQUAL 0 OR error MATCHES "Invalid allocator configuration was accepted")
    message(FATAL_ERROR "Expected allocator configuration refusal for ${mode}")
  endif()
endforeach()
