// Generated by tools/gen_function_models.py; do not edit.
functions {

  real logical_probe(real x) {
    if (x > 0) return logical_negation(x > 0);
    return 2.0;
  }
  real probe(real x) { return x; }
  real probe(vector x) {
    real out = 0;
    for (i in 1:num_elements(x)) out += (1 + i * 0.125) * x[i];
    return out;
  }
  real probe(row_vector x) {
    real out = 0;
    for (i in 1:num_elements(x)) out += (1 + i * 0.125) * x[i];
    return out;
  }
  real probe(matrix x) {
    real out = 0;
    for (j in 1:cols(x)) for (i in 1:rows(x))
      out += (1 + (i + (j - 1) * rows(x)) * 0.125) * x[i,j];
    return out;
  }
  real probe(array[] real x) {
    real out = 0;
    for (i in 1:size(x)) out += (1 + i * 0.125) * x[i];
    return out;
  }
  real probe(array[] int x) {
    real out = 0;
    for (i in 1:size(x)) out += (1 + i * 0.125) * x[i];
    return out;
  }
  real probe(array[] vector x) {
    real out = 0;
    for (i in 1:size(x)) out += (1 + i * 0.125) * probe(x[i]);
    return out;
  }
}
transformed data {

  array[2,3] real a = {{1,2,3},{4,5,6}};
  matrix[2,3] m = [[1,0,2],[0,3,4]];
  vector[3] v = [0.5,1.5,2.5]';
  vector[38] observed;
  observed[1] = probe(choose(8, 3)); // choose
  observed[2] = probe(ceil(v)); // ceil
  observed[3] = probe(floor(v)); // floor
  observed[4] = probe(round(v)); // round
  observed[5] = probe(trunc(v)); // trunc
  observed[6] = probe(step(-0.5)); // step
  observed[7] = probe(is_inf(positive_infinity())); // is_inf
  observed[8] = probe(is_nan(0.0)); // is_nan
  observed[9] = probe(logical_eq(2.5, 2.5)); // logical_eq
  observed[10] = probe(logical_neq(1, 2.5)); // logical_neq
  observed[11] = probe(logical_lt(1, 2.5)); // logical_lt
  observed[12] = probe(logical_lte(2.5, 2.5)); // logical_lte
  observed[13] = probe(logical_gt(3.5, 2)); // logical_gt
  observed[14] = probe(logical_gte(2, 3.5)); // logical_gte
  observed[15] = probe(logical_and(2, 0)); // logical_and
  observed[16] = probe(logical_or(0, 3)); // logical_or
  observed[17] = probe(is_nan(not_a_number())); // not_a_number
  observed[18] = probe(machine_precision()); // machine_precision
  observed[19] = probe(is_inf(negative_infinity())); // negative_infinity
  observed[20] = probe(is_inf(positive_infinity())); // positive_infinity
  observed[21] = probe(pi()); // pi
  observed[22] = probe(linspaced_array(3, -1.5, 2.5)); // linspaced_array
  observed[23] = probe(linspaced_int_array(5, 2, 3)); // linspaced_int_array
  observed[24] = probe(linspaced_vector(4, 0.0, 1.0)); // linspaced_vector
  observed[25] = probe(linspaced_row_vector(3, 2.0, 8.0)); // linspaced_row_vector
  observed[26] = probe(zeros_vector(3)); // zeros_vector
  observed[27] = probe(zeros_row_vector(3)); // zeros_row_vector
  observed[28] = probe(zeros_int_array(3)); // zeros_int_array
  observed[29] = probe(ones_array(3)); // ones_array
  observed[30] = probe(ones_vector(3)); // ones_vector
  observed[31] = probe(ones_row_vector(3)); // ones_row_vector
  observed[32] = probe(identity_matrix(3)); // identity_matrix
  observed[33] = probe(csr_extract_u(m)); // csr_extract_u
  observed[34] = probe(csr_extract_v(m)); // csr_extract_v
  observed[35] = probe(csr_extract_w(m)); // csr_extract_w
  observed[36] = probe(to_matrix(a)); // to_matrix
  observed[37] = probe(hypergeometric_lpmf(2 | 4, 5, 7)); // hypergeometric_lpmf
  observed[38] = probe(discrete_range_lpmf(2 | 1, 4)); // discrete_range_lpmf
}
parameters { real theta; }
model { target += (1 + theta) * sum(observed); }
generated quantities { vector[38] values = observed; }
