// Generated by tools/gen_function_models.py; do not edit.
functions {
  vector coverage_jacobian(vector theta) {
    vector[49] values;
    {
      // abs(real)=>real
      real contribution = 0;
      contribution += 1 * abs((0.5 + 0.0625 * theta[1]));
      values[1] = contribution;
    }
    {
      // asinh(real)=>real
      real contribution = 0;
      contribution += 1 * asinh((0.5 + 0.0625 * theta[2]));
      values[2] = contribution;
    }
    {
      // bernoulli_lccdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * bernoulli_lccdf(0 | (0.40000000000000002 + 0.0625 * theta[3]));
      values[3] = contribution;
    }
    {
      // bessel_second_kind(int,real)=>real
      real contribution = 0;
      contribution += 1 * bessel_second_kind(2, (1.3999999999999999 + 0.0625 * theta[4]));
      values[4] = contribution;
    }
    {
      // beta_binomial_lpmf(int,int,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_binomial_lpmf(3 | 10, (2 + 0.0625 * theta[5]), (3 + 0.0625 * theta[6]));
      values[5] = contribution;
    }
    {
      // beta_neg_binomial_cdf(int,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_neg_binomial_cdf(3 | (2 + 0.0625 * theta[7]), (3 + 0.0625 * theta[8]), (1.3 + 0.0625 * theta[9]));
      values[6] = contribution;
    }
    {
      // beta_proportion_lcdf(real,real,int)=>real
      real contribution = 0;
      contribution += 1 * beta_proportion_lcdf((0.40000000000000002 + 0.0625 * theta[10]) | (0.59999999999999998 + 0.0625 * theta[11]), 2);
      values[7] = contribution;
    }
    {
      // binomial_lcdf(int,int,real)=>real
      real contribution = 0;
      contribution += 1 * binomial_lcdf(3 | 10, (0.40000000000000002 + 0.0625 * theta[12]));
      values[8] = contribution;
    }
    {
      // cauchy_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * cauchy_lcdf((0.40000000000000002 + 0.0625 * theta[13]) | (0.20000000000000001 + 0.0625 * theta[14]), (1.3 + 0.0625 * theta[15]));
      values[9] = contribution;
    }
    {
      // chi_square_lcdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * chi_square_lcdf((1.3999999999999999 + 0.0625 * theta[16]) | (3 + 0.0625 * theta[17]));
      values[10] = contribution;
    }
    {
      // divide(real,real)=>real
      real contribution = 0;
      contribution += 1 * divide((0.5 + 0.0625 * theta[18]), (1.25 + 0.0625 * theta[19]));
      values[11] = contribution;
    }
    {
      // elt_divide(real,real)=>real
      real contribution = 0;
      contribution += 1 * elt_divide((0.5 + 0.0625 * theta[20]), (1.25 + 0.0625 * theta[21]));
      values[12] = contribution;
    }
    {
      // exp2(real)=>real
      real contribution = 0;
      contribution += 1 * exp2((0.5 + 0.0625 * theta[22]));
      values[13] = contribution;
    }
    {
      // expm1(real)=>real
      real contribution = 0;
      contribution += 1 * expm1((0.5 + 0.0625 * theta[23]));
      values[14] = contribution;
    }
    {
      // falling_factorial(real,int)=>real
      real contribution = 0;
      contribution += 1 * falling_factorial((3.5 + 0.0625 * theta[24]), 2);
      values[15] = contribution;
    }
    {
      // fmod(int,real)=>real
      real contribution = 0;
      contribution += 1 * fmod(2, (0.5 + 0.0625 * theta[25]));
      values[16] = contribution;
    }
    {
      // gamma_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gamma_cdf((1.3999999999999999 + 0.0625 * theta[26]) | (2 + 0.0625 * theta[27]), (1.3 + 0.0625 * theta[28]));
      values[17] = contribution;
    }
    {
      // gamma_q(real,real)=>real
      real contribution = 0;
      contribution += 1 * gamma_q((2 + 0.0625 * theta[29]), (1.3 + 0.0625 * theta[30]));
      values[18] = contribution;
    }
    {
      // hypot(int,real)=>real
      real contribution = 0;
      contribution += 1 * hypot(2, (0.5 + 0.0625 * theta[31]));
      values[19] = contribution;
    }
    {
      // inv_chi_square_lcdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_chi_square_lcdf((1.3999999999999999 + 0.0625 * theta[32]) | (3 + 0.0625 * theta[33]));
      values[20] = contribution;
    }
    {
      // inv_gamma_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_gamma_lccdf((1.3999999999999999 + 0.0625 * theta[34]) | (2 + 0.0625 * theta[35]), (1.3 + 0.0625 * theta[36]));
      values[21] = contribution;
    }
    {
      // inv_square(real)=>real
      real contribution = 0;
      contribution += 1 * inv_square((0.5 + 0.0625 * theta[37]));
      values[22] = contribution;
    }
    {
      // ldexp(real,int)=>real
      real contribution = 0;
      contribution += 1 * ldexp((0.5 + 0.0625 * theta[38]), 2);
      values[23] = contribution;
    }
    {
      // log10(real)=>real
      real contribution = 0;
      contribution += 1 * log10((1.3999999999999999 + 0.0625 * theta[39]));
      values[24] = contribution;
    }
    {
      // log1p_exp(real)=>real
      real contribution = 0;
      contribution += 1 * log1p_exp((0.5 + 0.0625 * theta[40]));
      values[25] = contribution;
    }
    {
      // log_inv_logit_diff(int,real)=>real
      real contribution = 0;
      contribution += 1 * log_inv_logit_diff(2, (0.5 + 0.0625 * theta[41]));
      values[26] = contribution;
    }
    {
      // logistic_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * logistic_cdf((0.40000000000000002 + 0.0625 * theta[42]) | (0.20000000000000001 + 0.0625 * theta[43]), (1.3 + 0.0625 * theta[44]));
      values[27] = contribution;
    }
    {
      // loglogistic_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * loglogistic_cdf((1.3999999999999999 + 0.0625 * theta[45]) | (2 + 0.0625 * theta[46]), (1.3 + 0.0625 * theta[47]));
      values[28] = contribution;
    }
    {
      // lognormal_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lognormal_lpdf((1.3999999999999999 + 0.0625 * theta[48]) | (0.20000000000000001 + 0.0625 * theta[49]), (1.3 + 0.0625 * theta[50]));
      values[29] = contribution;
    }
    {
      // lower_upper_bound_jacobian(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lower_upper_bound_jacobian((0 + 0.0625 * theta[51]), (-1 + 0.0625 * theta[52]), (1 + 0.0625 * theta[53]));
      values[30] = contribution;
    }
    {
      // multiply(real,real)=>real
      real contribution = 0;
      contribution += 1 * multiply((0.5 + 0.0625 * theta[54]), (1.25 + 0.0625 * theta[55]));
      values[31] = contribution;
    }
    {
      // neg_binomial_2_lpmf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_2_lpmf(3 | (2 + 0.0625 * theta[56]), (1.3 + 0.0625 * theta[57]));
      values[32] = contribution;
    }
    {
      // normal_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * normal_cdf((0.40000000000000002 + 0.0625 * theta[58]) | (0.20000000000000001 + 0.0625 * theta[59]), (1.3 + 0.0625 * theta[60]));
      values[33] = contribution;
    }
    {
      // offset_multiplier_jacobian(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * offset_multiplier_jacobian((0.5 + 0.0625 * theta[61]), (1.25 + 0.0625 * theta[62]), (0.75 + 0.0625 * theta[63]));
      values[34] = contribution;
    }
    {
      // pareto_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_lcdf((2.3999999999999999 + 0.0625 * theta[64]) | (1 + 0.0625 * theta[65]), (1.3 + 0.0625 * theta[66]));
      values[35] = contribution;
    }
    {
      // pareto_type_2_lpdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_type_2_lpdf((1.3999999999999999 + 0.0625 * theta[67]) | (0 + 0.0625 * theta[68]), (1.2 + 0.0625 * theta[69]), (1.3 + 0.0625 * theta[70]));
      values[36] = contribution;
    }
    {
      // poisson_log_lpmf(int,real)=>real
      real contribution = 0;
      contribution += 1 * poisson_log_lpmf(3 | (0.40000000000000002 + 0.0625 * theta[71]));
      values[37] = contribution;
    }
    {
      // rayleigh_lcdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * rayleigh_lcdf((1.3999999999999999 + 0.0625 * theta[72]) | (1.3 + 0.0625 * theta[73]));
      values[38] = contribution;
    }
    {
      // scaled_inv_chi_square_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * scaled_inv_chi_square_lcdf((1.3999999999999999 + 0.0625 * theta[74]) | (3 + 0.0625 * theta[75]), (1.2 + 0.0625 * theta[76]));
      values[39] = contribution;
    }
    {
      // skew_double_exponential_lccdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_double_exponential_lccdf((0.40000000000000002 + 0.0625 * theta[77]) | (0.20000000000000001 + 0.0625 * theta[78]), (1.3 + 0.0625 * theta[79]), (0.59999999999999998 + 0.0625 * theta[80]));
      values[40] = contribution;
    }
    {
      // skew_normal_lcdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_normal_lcdf((0.40000000000000002 + 0.0625 * theta[81]) | (0.20000000000000001 + 0.0625 * theta[82]), (1.3 + 0.0625 * theta[83]), (0.69999999999999996 + 0.0625 * theta[84]));
      values[41] = contribution;
    }
    {
      // std_normal_cdf(real)=>real
      real contribution = 0;
      contribution += 1 * std_normal_cdf((0.40000000000000002 + 0.0625 * theta[85]));
      values[42] = contribution;
    }
    {
      // std_normal_qf(real)=>real
      real contribution = 0;
      contribution += 1 * std_normal_qf((0.5 + 0.0625 * theta[86]));
      values[43] = contribution;
    }
    {
      // student_t_qf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * student_t_qf((0.29999999999999999 + 0.0625 * theta[87]), (5 + 0.0625 * theta[88]), (0.10000000000000001 + 0.0625 * theta[89]), (1.2 + 0.0625 * theta[90]));
      values[44] = contribution;
    }
    {
      // trigamma(real)=>real
      real contribution = 0;
      contribution += 1 * trigamma((1.3999999999999999 + 0.0625 * theta[91]));
      values[45] = contribution;
    }
    {
      // upper_bound_constrain(real,real)=>real
      real contribution = 0;
      contribution += 1 * upper_bound_constrain((0.5 + 0.0625 * theta[92]), (1.25 + 0.0625 * theta[93]));
      values[46] = contribution;
    }
    {
      // von_mises_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * von_mises_lcdf((0.40000000000000002 + 0.0625 * theta[94]) | (0.20000000000000001 + 0.0625 * theta[95]), (1.3 + 0.0625 * theta[96]));
      values[47] = contribution;
    }
    {
      // weibull_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * weibull_lpdf((1.3999999999999999 + 0.0625 * theta[97]) | (2 + 0.0625 * theta[98]), (1.3 + 0.0625 * theta[99]));
      values[48] = contribution;
    }
    {
      // yule_simon_lpmf(int,real)=>real
      real contribution = 0;
      contribution += 1 * yule_simon_lpmf(3 | (1.3 + 0.0625 * theta[100]));
      values[49] = contribution;
    }
    return values;
  }
}
parameters { vector[100] theta; }
transformed parameters {
  vector[49] observed = coverage_jacobian(theta);
}
model { target += sum(observed); }
