// Generated by tools/gen_function_models.py; do not edit.
functions {
  vector coverage_jacobian(vector theta) {
    vector[48] values;
    {
      // acos(real)=>real
      real contribution = 0;
      contribution += 1 * acos((0.34999999999999998 + 0.0625 * theta[1]));
      values[1] = contribution;
    }
    {
      // atan(real)=>real
      real contribution = 0;
      contribution += 1 * atan((0.5 + 0.0625 * theta[2]));
      values[2] = contribution;
    }
    {
      // bernoulli_lcdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * bernoulli_lcdf(0 | (0.40000000000000002 + 0.0625 * theta[3]));
      values[3] = contribution;
    }
    {
      // beta(int,real)=>real
      real contribution = 0;
      contribution += 1 * beta(2, (2 + 0.0625 * theta[4]));
      values[4] = contribution;
    }
    {
      // beta_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_cdf((0.40000000000000002 + 0.0625 * theta[5]) | (2 + 0.0625 * theta[6]), (1.3 + 0.0625 * theta[7]));
      values[5] = contribution;
    }
    {
      // beta_neg_binomial_lccdf(int,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_neg_binomial_lccdf(3 | (2 + 0.0625 * theta[8]), (3 + 0.0625 * theta[9]), (1.3 + 0.0625 * theta[10]));
      values[6] = contribution;
    }
    {
      // beta_proportion_lpdf(real,real,int)=>real
      real contribution = 0;
      contribution += 1 * beta_proportion_lpdf((0.40000000000000002 + 0.0625 * theta[11]) | (0.59999999999999998 + 0.0625 * theta[12]), 2);
      values[7] = contribution;
    }
    {
      // binomial_logit_lpmf(int,int,real)=>real
      real contribution = 0;
      contribution += 1 * binomial_logit_lpmf(3 | 10, (0.40000000000000002 + 0.0625 * theta[13]));
      values[8] = contribution;
    }
    {
      // cauchy_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * cauchy_lpdf((0.40000000000000002 + 0.0625 * theta[14]) | (0.20000000000000001 + 0.0625 * theta[15]), (1.3 + 0.0625 * theta[16]));
      values[9] = contribution;
    }
    {
      // chi_square_lpdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * chi_square_lpdf((1.3999999999999999 + 0.0625 * theta[17]) | (3 + 0.0625 * theta[18]));
      values[10] = contribution;
    }
    {
      // double_exponential_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * double_exponential_cdf((0.40000000000000002 + 0.0625 * theta[19]) | (0.20000000000000001 + 0.0625 * theta[20]), (1.3 + 0.0625 * theta[21]));
      values[11] = contribution;
    }
    {
      // elt_multiply(real,real)=>real
      real contribution = 0;
      contribution += 1 * elt_multiply((0.5 + 0.0625 * theta[22]), (1.25 + 0.0625 * theta[23]));
      values[12] = contribution;
    }
    {
      // exp_mod_normal_cdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * exp_mod_normal_cdf((0.40000000000000002 + 0.0625 * theta[24]) | (0.20000000000000001 + 0.0625 * theta[25]), (1.3 + 0.0625 * theta[26]), (0.69999999999999996 + 0.0625 * theta[27]));
      values[13] = contribution;
    }
    {
      // exponential_cdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * exponential_cdf((1.3999999999999999 + 0.0625 * theta[28]) | (0.69999999999999996 + 0.0625 * theta[29]));
      values[14] = contribution;
    }
    {
      // fdim(int,real)=>real
      real contribution = 0;
      contribution += 1 * fdim(2, (2 + 0.0625 * theta[30]));
      values[15] = contribution;
    }
    {
      // frechet_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * frechet_cdf((1.3999999999999999 + 0.0625 * theta[31]) | (2 + 0.0625 * theta[32]), (1.3 + 0.0625 * theta[33]));
      values[16] = contribution;
    }
    {
      // gamma_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gamma_lccdf((1.3999999999999999 + 0.0625 * theta[34]) | (2 + 0.0625 * theta[35]), (1.3 + 0.0625 * theta[36]));
      values[17] = contribution;
    }
    {
      // gumbel_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gumbel_cdf((0.40000000000000002 + 0.0625 * theta[37]) | (0.20000000000000001 + 0.0625 * theta[38]), (1.3 + 0.0625 * theta[39]));
      values[18] = contribution;
    }
    {
      // inv(real)=>real
      real contribution = 0;
      contribution += 1 * inv((0.5 + 0.0625 * theta[40]));
      values[19] = contribution;
    }
    {
      // inv_chi_square_lpdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_chi_square_lpdf((1.3999999999999999 + 0.0625 * theta[41]) | (3 + 0.0625 * theta[42]));
      values[20] = contribution;
    }
    {
      // inv_gamma_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_gamma_lcdf((1.3999999999999999 + 0.0625 * theta[43]) | (2 + 0.0625 * theta[44]), (1.3 + 0.0625 * theta[45]));
      values[21] = contribution;
    }
    {
      // lambert_w0(real)=>real
      real contribution = 0;
      contribution += 1 * lambert_w0((0.5 + 0.0625 * theta[46]));
      values[22] = contribution;
    }
    {
      // lgamma(real)=>real
      real contribution = 0;
      contribution += 1 * lgamma((1.3999999999999999 + 0.0625 * theta[47]));
      values[23] = contribution;
    }
    {
      // log1m(real)=>real
      real contribution = 0;
      contribution += 1 * log1m((0.34999999999999998 + 0.0625 * theta[48]));
      values[24] = contribution;
    }
    {
      // log2(real)=>real
      real contribution = 0;
      contribution += 1 * log2((1.3999999999999999 + 0.0625 * theta[49]));
      values[25] = contribution;
    }
    {
      // log_mix(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * log_mix((0.34999999999999998 + 0.0625 * theta[50]), (-0.20000000000000001 + 0.0625 * theta[51]), (0.69999999999999996 + 0.0625 * theta[52]));
      values[26] = contribution;
    }
    {
      // logistic_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * logistic_lccdf((0.40000000000000002 + 0.0625 * theta[53]) | (0.20000000000000001 + 0.0625 * theta[54]), (1.3 + 0.0625 * theta[55]));
      values[27] = contribution;
    }
    {
      // loglogistic_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * loglogistic_lpdf((1.3999999999999999 + 0.0625 * theta[56]) | (2 + 0.0625 * theta[57]), (1.3 + 0.0625 * theta[58]));
      values[28] = contribution;
    }
    {
      // lower_bound_constrain(real,real)=>real
      real contribution = 0;
      contribution += 1 * lower_bound_constrain((0.5 + 0.0625 * theta[59]), (1.25 + 0.0625 * theta[60]));
      values[29] = contribution;
    }
    {
      // lower_upper_bound_unconstrain(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lower_upper_bound_unconstrain((0 + 0.0625 * theta[61]), (-1 + 0.0625 * theta[62]), (1 + 0.0625 * theta[63]));
      values[30] = contribution;
    }
    {
      // neg_binomial_2_cdf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_2_cdf(3 | (2 + 0.0625 * theta[64]), (1.3 + 0.0625 * theta[65]));
      values[31] = contribution;
    }
    {
      // neg_binomial_cdf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_cdf(3 | (2 + 0.0625 * theta[66]), (1.3 + 0.0625 * theta[67]));
      values[32] = contribution;
    }
    {
      // normal_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * normal_lccdf((0.40000000000000002 + 0.0625 * theta[68]) | (0.20000000000000001 + 0.0625 * theta[69]), (1.3 + 0.0625 * theta[70]));
      values[33] = contribution;
    }
    {
      // offset_multiplier_unconstrain(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * offset_multiplier_unconstrain((0.5 + 0.0625 * theta[71]), (1.25 + 0.0625 * theta[72]), (0.75 + 0.0625 * theta[73]));
      values[34] = contribution;
    }
    {
      // pareto_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_lpdf((2.3999999999999999 + 0.0625 * theta[74]) | (1 + 0.0625 * theta[75]), (1.3 + 0.0625 * theta[76]));
      values[35] = contribution;
    }
    {
      // plus(real)=>real
      real contribution = 0;
      contribution += 1 * plus((0.5 + 0.0625 * theta[77]));
      values[36] = contribution;
    }
    {
      // poisson_lpmf(int,real)=>real
      real contribution = 0;
      contribution += 1 * poisson_lpmf(3 | (1.3 + 0.0625 * theta[78]));
      values[37] = contribution;
    }
    {
      // rayleigh_lpdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * rayleigh_lpdf((1.3999999999999999 + 0.0625 * theta[79]) | (1.3 + 0.0625 * theta[80]));
      values[38] = contribution;
    }
    {
      // scaled_inv_chi_square_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * scaled_inv_chi_square_lpdf((1.3999999999999999 + 0.0625 * theta[81]) | (3 + 0.0625 * theta[82]), (1.2 + 0.0625 * theta[83]));
      values[39] = contribution;
    }
    {
      // skew_double_exponential_lcdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_double_exponential_lcdf((0.40000000000000002 + 0.0625 * theta[84]) | (0.20000000000000001 + 0.0625 * theta[85]), (1.3 + 0.0625 * theta[86]), (0.59999999999999998 + 0.0625 * theta[87]));
      values[40] = contribution;
    }
    {
      // skew_normal_lpdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_normal_lpdf((0.40000000000000002 + 0.0625 * theta[88]) | (0.20000000000000001 + 0.0625 * theta[89]), (1.3 + 0.0625 * theta[90]), (0.69999999999999996 + 0.0625 * theta[91]));
      values[41] = contribution;
    }
    {
      // std_normal_lccdf(real)=>real
      real contribution = 0;
      contribution += 1 * std_normal_lccdf((0.40000000000000002 + 0.0625 * theta[92]));
      values[42] = contribution;
    }
    {
      // student_t_cdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * student_t_cdf((0.40000000000000002 + 0.0625 * theta[93]) | (3 + 0.0625 * theta[94]), (0.20000000000000001 + 0.0625 * theta[95]), (1.3 + 0.0625 * theta[96]));
      values[43] = contribution;
    }
    {
      // subtract(real,real)=>real
      real contribution = 0;
      contribution += 1 * subtract((0.5 + 0.0625 * theta[97]), (1.25 + 0.0625 * theta[98]));
      values[44] = contribution;
    }
    {
      // uniform_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * uniform_cdf((0.40000000000000002 + 0.0625 * theta[99]) | (-1 + 0.0625 * theta[100]), (1.5 + 0.0625 * theta[101]));
      values[45] = contribution;
    }
    {
      // upper_bound_jacobian(real,real)=>real
      real contribution = 0;
      contribution += 1 * upper_bound_jacobian((0.5 + 0.0625 * theta[102]), (1.25 + 0.0625 * theta[103]));
      values[46] = contribution;
    }
    {
      // von_mises_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * von_mises_lpdf((0.40000000000000002 + 0.0625 * theta[104]) | (0.20000000000000001 + 0.0625 * theta[105]), (1.3 + 0.0625 * theta[106]));
      values[47] = contribution;
    }
    {
      // wiener_lpdf(real,real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * wiener_lpdf((1.5 + 0.03125 * theta[107]) | (1.2 + 0.03125 * theta[108]), (0.20000000000000001 + 0.03125 * theta[109]), (0.45000000000000001 + 0.03125 * theta[110]), (0.10000000000000001 + 0.03125 * theta[111]));
      values[48] = contribution;
    }
    return values;
  }
}
parameters { vector[111] theta; }
transformed parameters {
  vector[48] observed = coverage_jacobian(theta);
}
model { target += sum(observed); }
