// Generated by tools/gen_function_models.py; do not edit.
functions {
  vector coverage_jacobian(vector theta) {
    vector[49] values;
    {
      // Phi(real)=>real
      real contribution = 0;
      contribution += 1 * Phi((0.5 + 0.0625 * theta[1]));
      values[1] = contribution;
    }
    {
      // add(real,real)=>real
      real contribution = 0;
      contribution += 1 * add((0.5 + 0.0625 * theta[2]), (1.25 + 0.0625 * theta[3]));
      values[2] = contribution;
    }
    {
      // atanh(real)=>real
      real contribution = 0;
      contribution += 1 * atanh((0.34999999999999998 + 0.0625 * theta[4]));
      values[3] = contribution;
    }
    {
      // bernoulli_lpmf(int,real)=>real
      real contribution = 0;
      contribution += 1 * bernoulli_lpmf(0 | (0.40000000000000002 + 0.0625 * theta[5]));
      values[4] = contribution;
    }
    {
      // beta_binomial_lccdf(int,int,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_binomial_lccdf(3 | 10, (2 + 0.0625 * theta[6]), (3 + 0.0625 * theta[7]));
      values[5] = contribution;
    }
    {
      // beta_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_lcdf((0.40000000000000002 + 0.0625 * theta[8]) | (2 + 0.0625 * theta[9]), (1.3 + 0.0625 * theta[10]));
      values[6] = contribution;
    }
    {
      // beta_neg_binomial_lpmf(int,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_neg_binomial_lpmf(3 | (2 + 0.0625 * theta[11]), (3 + 0.0625 * theta[12]), (1.3 + 0.0625 * theta[13]));
      values[7] = contribution;
    }
    {
      // binomial_cdf(int,int,real)=>real
      real contribution = 0;
      contribution += 1 * binomial_cdf(3 | 10, (0.40000000000000002 + 0.0625 * theta[14]));
      values[8] = contribution;
    }
    {
      // cauchy_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * cauchy_cdf((0.40000000000000002 + 0.0625 * theta[15]) | (0.20000000000000001 + 0.0625 * theta[16]), (1.3 + 0.0625 * theta[17]));
      values[9] = contribution;
    }
    {
      // chi_square_cdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * chi_square_cdf((1.3999999999999999 + 0.0625 * theta[18]) | (3 + 0.0625 * theta[19]));
      values[10] = contribution;
    }
    {
      // cosh(real)=>real
      real contribution = 0;
      contribution += 1 * cosh((0.5 + 0.0625 * theta[20]));
      values[11] = contribution;
    }
    {
      // double_exponential_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * double_exponential_lcdf((0.40000000000000002 + 0.0625 * theta[21]) | (0.20000000000000001 + 0.0625 * theta[22]), (1.3 + 0.0625 * theta[23]));
      values[12] = contribution;
    }
    {
      // erfc(real)=>real
      real contribution = 0;
      contribution += 1 * erfc((0.5 + 0.0625 * theta[24]));
      values[13] = contribution;
    }
    {
      // exp_mod_normal_lcdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * exp_mod_normal_lcdf((0.40000000000000002 + 0.0625 * theta[25]) | (0.20000000000000001 + 0.0625 * theta[26]), (1.3 + 0.0625 * theta[27]), (0.69999999999999996 + 0.0625 * theta[28]));
      values[14] = contribution;
    }
    {
      // exponential_lcdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * exponential_lcdf((1.3999999999999999 + 0.0625 * theta[29]) | (0.69999999999999996 + 0.0625 * theta[30]));
      values[15] = contribution;
    }
    {
      // fmax(int,real)=>real
      real contribution = 0;
      contribution += 1 * fmax(2, (2 + 0.0625 * theta[31]));
      values[16] = contribution;
    }
    {
      // frechet_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * frechet_lcdf((1.3999999999999999 + 0.0625 * theta[32]) | (2 + 0.0625 * theta[33]), (1.3 + 0.0625 * theta[34]));
      values[17] = contribution;
    }
    {
      // gamma_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gamma_lpdf((1.3999999999999999 + 0.0625 * theta[35]) | (2 + 0.0625 * theta[36]), (1.3 + 0.0625 * theta[37]));
      values[18] = contribution;
    }
    {
      // gumbel_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gumbel_lcdf((0.40000000000000002 + 0.0625 * theta[38]) | (0.20000000000000001 + 0.0625 * theta[39]), (1.3 + 0.0625 * theta[40]));
      values[19] = contribution;
    }
    {
      // inv_chi_square_cdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_chi_square_cdf((1.3999999999999999 + 0.0625 * theta[41]) | (3 + 0.0625 * theta[42]));
      values[20] = contribution;
    }
    {
      // inv_erfc(real)=>real
      real contribution = 0;
      contribution += 1 * inv_erfc((0.5 + 0.0625 * theta[43]));
      values[21] = contribution;
    }
    {
      // inv_logit(real)=>real
      real contribution = 0;
      contribution += 1 * inv_logit((0.5 + 0.0625 * theta[44]));
      values[22] = contribution;
    }
    {
      // lbeta(int,real)=>real
      real contribution = 0;
      contribution += 1 * lbeta(2, (2 + 0.0625 * theta[45]));
      values[23] = contribution;
    }
    {
      // lmultiply(int,real)=>real
      real contribution = 0;
      contribution += 1 * lmultiply(2, (0.5 + 0.0625 * theta[46]));
      values[24] = contribution;
    }
    {
      // log1m_inv_logit(real)=>real
      real contribution = 0;
      contribution += 1 * log1m_inv_logit((0.5 + 0.0625 * theta[47]));
      values[25] = contribution;
    }
    {
      // log_falling_factorial(int,real)=>real
      real contribution = 0;
      contribution += 1 * log_falling_factorial(2, (3.5 + 0.0625 * theta[48]));
      values[26] = contribution;
    }
    {
      // log_rising_factorial(int,real)=>real
      real contribution = 0;
      contribution += 1 * log_rising_factorial(2, (1.5 + 0.0625 * theta[49]));
      values[27] = contribution;
    }
    {
      // logistic_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * logistic_lpdf((0.40000000000000002 + 0.0625 * theta[50]) | (0.20000000000000001 + 0.0625 * theta[51]), (1.3 + 0.0625 * theta[52]));
      values[28] = contribution;
    }
    {
      // lognormal_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lognormal_lccdf((1.3999999999999999 + 0.0625 * theta[53]) | (0.20000000000000001 + 0.0625 * theta[54]), (1.3 + 0.0625 * theta[55]));
      values[29] = contribution;
    }
    {
      // lower_bound_unconstrain(real,real)=>real
      real contribution = 0;
      contribution += 1 * lower_bound_unconstrain((1.5 + 0.0625 * theta[56]), (0.5 + 0.0625 * theta[57]));
      values[30] = contribution;
    }
    {
      // modified_bessel_first_kind(int,real)=>real
      real contribution = 0;
      contribution += 1 * modified_bessel_first_kind(2, (1.3999999999999999 + 0.0625 * theta[58]));
      values[31] = contribution;
    }
    {
      // neg_binomial_2_lcdf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_2_lcdf(3 | (2 + 0.0625 * theta[59]), (1.3 + 0.0625 * theta[60]));
      values[32] = contribution;
    }
    {
      // neg_binomial_lcdf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_lcdf(3 | (2 + 0.0625 * theta[61]), (1.3 + 0.0625 * theta[62]));
      values[33] = contribution;
    }
    {
      // normal_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * normal_lpdf((0.40000000000000002 + 0.0625 * theta[63]) | (0.20000000000000001 + 0.0625 * theta[64]), (1.3 + 0.0625 * theta[65]));
      values[34] = contribution;
    }
    {
      // pareto_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_cdf((2.3999999999999999 + 0.0625 * theta[66]) | (1 + 0.0625 * theta[67]), (1.3 + 0.0625 * theta[68]));
      values[35] = contribution;
    }
    {
      // pareto_type_2_lccdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_type_2_lccdf((1.3999999999999999 + 0.0625 * theta[69]) | (0 + 0.0625 * theta[70]), (1.2 + 0.0625 * theta[71]), (1.3 + 0.0625 * theta[72]));
      values[36] = contribution;
    }
    {
      // poisson_lccdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * poisson_lccdf(3 | (1.3 + 0.0625 * theta[73]));
      values[37] = contribution;
    }
    {
      // rayleigh_cdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * rayleigh_cdf((1.3999999999999999 + 0.0625 * theta[74]) | (1.3 + 0.0625 * theta[75]));
      values[38] = contribution;
    }
    {
      // scaled_inv_chi_square_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * scaled_inv_chi_square_cdf((1.3999999999999999 + 0.0625 * theta[76]) | (3 + 0.0625 * theta[77]), (1.2 + 0.0625 * theta[78]));
      values[39] = contribution;
    }
    {
      // sinh(real)=>real
      real contribution = 0;
      contribution += 1 * sinh((0.5 + 0.0625 * theta[79]));
      values[40] = contribution;
    }
    {
      // skew_normal_cdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_normal_cdf((0.40000000000000002 + 0.0625 * theta[80]) | (0.20000000000000001 + 0.0625 * theta[81]), (1.3 + 0.0625 * theta[82]), (0.69999999999999996 + 0.0625 * theta[83]));
      values[41] = contribution;
    }
    {
      // square(real)=>real
      real contribution = 0;
      contribution += 1 * square((0.5 + 0.0625 * theta[84]));
      values[42] = contribution;
    }
    {
      // std_normal_log_qf(real)=>real
      real contribution = 0;
      contribution += 1 * std_normal_log_qf((-0.5 + 0.0625 * theta[85]));
      values[43] = contribution;
    }
    {
      // student_t_lcdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * student_t_lcdf((0.40000000000000002 + 0.0625 * theta[86]) | (3 + 0.0625 * theta[87]), (0.20000000000000001 + 0.0625 * theta[88]), (1.3 + 0.0625 * theta[89]));
      values[44] = contribution;
    }
    {
      // tanh(real)=>real
      real contribution = 0;
      contribution += 1 * tanh((0.5 + 0.0625 * theta[90]));
      values[45] = contribution;
    }
    {
      // uniform_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * uniform_lcdf((0.40000000000000002 + 0.0625 * theta[91]) | (-1 + 0.0625 * theta[92]), (1.5 + 0.0625 * theta[93]));
      values[46] = contribution;
    }
    {
      // von_mises_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * von_mises_cdf((0.40000000000000002 + 0.0625 * theta[94]) | (0.20000000000000001 + 0.0625 * theta[95]), (1.3 + 0.0625 * theta[96]));
      values[47] = contribution;
    }
    {
      // weibull_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * weibull_lccdf((1.3999999999999999 + 0.0625 * theta[97]) | (2 + 0.0625 * theta[98]), (1.3 + 0.0625 * theta[99]));
      values[48] = contribution;
    }
    {
      // yule_simon_lccdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * yule_simon_lccdf(3 | (1.3 + 0.0625 * theta[100]));
      values[49] = contribution;
    }
    return values;
  }
}
parameters { vector[100] theta; }
transformed parameters {
  vector[49] observed = coverage_jacobian(theta);
}
model { target += sum(observed); }
