// Generated by tools/gen_function_models.py; do not edit.
functions {
  vector coverage_jacobian(vector theta) {
    vector[48] values;
    {
      // acosh(real)=>real
      real contribution = 0;
      contribution += 1 * acosh((1.3999999999999999 + 0.0625 * theta[1]));
      values[1] = contribution;
    }
    {
      // atan2(int,real)=>real
      real contribution = 0;
      contribution += 1 * atan2(2, (0.5 + 0.0625 * theta[2]));
      values[2] = contribution;
    }
    {
      // bernoulli_logit_lpmf(int,real)=>real
      real contribution = 0;
      contribution += 1 * bernoulli_logit_lpmf(0 | (0.40000000000000002 + 0.0625 * theta[3]));
      values[3] = contribution;
    }
    {
      // beta_binomial_cdf(int,int,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_binomial_cdf(3 | 10, (2 + 0.0625 * theta[4]), (3 + 0.0625 * theta[5]));
      values[4] = contribution;
    }
    {
      // beta_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_lccdf((0.40000000000000002 + 0.0625 * theta[6]) | (2 + 0.0625 * theta[7]), (1.3 + 0.0625 * theta[8]));
      values[5] = contribution;
    }
    {
      // beta_neg_binomial_lcdf(int,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_neg_binomial_lcdf(3 | (2 + 0.0625 * theta[9]), (3 + 0.0625 * theta[10]), (1.3 + 0.0625 * theta[11]));
      values[6] = contribution;
    }
    {
      // binary_log_loss(int,real)=>real
      real contribution = 0;
      contribution += 1 * binary_log_loss(2, (0.5 + 0.0625 * theta[12]));
      values[7] = contribution;
    }
    {
      // binomial_lpmf(int,int,real)=>real
      real contribution = 0;
      contribution += 1 * binomial_lpmf(3 | 10, (0.40000000000000002 + 0.0625 * theta[13]));
      values[8] = contribution;
    }
    {
      // cbrt(real)=>real
      real contribution = 0;
      contribution += 1 * cbrt((0.5 + 0.0625 * theta[14]));
      values[9] = contribution;
    }
    {
      // cos(real)=>real
      real contribution = 0;
      contribution += 1 * cos((0.5 + 0.0625 * theta[15]));
      values[10] = contribution;
    }
    {
      // double_exponential_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * double_exponential_lccdf((0.40000000000000002 + 0.0625 * theta[16]) | (0.20000000000000001 + 0.0625 * theta[17]), (1.3 + 0.0625 * theta[18]));
      values[11] = contribution;
    }
    {
      // erf(real)=>real
      real contribution = 0;
      contribution += 1 * erf((0.5 + 0.0625 * theta[19]));
      values[12] = contribution;
    }
    {
      // exp_mod_normal_lccdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * exp_mod_normal_lccdf((0.40000000000000002 + 0.0625 * theta[20]) | (0.20000000000000001 + 0.0625 * theta[21]), (1.3 + 0.0625 * theta[22]), (0.69999999999999996 + 0.0625 * theta[23]));
      values[13] = contribution;
    }
    {
      // exponential_lccdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * exponential_lccdf((1.3999999999999999 + 0.0625 * theta[24]) | (0.69999999999999996 + 0.0625 * theta[25]));
      values[14] = contribution;
    }
    {
      // fma(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * fma((0.5 + 0.0625 * theta[26]), (1.25 + 0.0625 * theta[27]), (0.75 + 0.0625 * theta[28]));
      values[15] = contribution;
    }
    {
      // frechet_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * frechet_lccdf((1.3999999999999999 + 0.0625 * theta[29]) | (2 + 0.0625 * theta[30]), (1.3 + 0.0625 * theta[31]));
      values[16] = contribution;
    }
    {
      // gamma_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gamma_lcdf((1.3999999999999999 + 0.0625 * theta[32]) | (2 + 0.0625 * theta[33]), (1.3 + 0.0625 * theta[34]));
      values[17] = contribution;
    }
    {
      // gumbel_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gumbel_lccdf((0.40000000000000002 + 0.0625 * theta[35]) | (0.20000000000000001 + 0.0625 * theta[36]), (1.3 + 0.0625 * theta[37]));
      values[18] = contribution;
    }
    {
      // inv_Phi(real)=>real
      real contribution = 0;
      contribution += 1 * inv_Phi((0.5 + 0.0625 * theta[38]));
      values[19] = contribution;
    }
    {
      // inv_cloglog(real)=>real
      real contribution = 0;
      contribution += 1 * inv_cloglog((0.5 + 0.0625 * theta[39]));
      values[20] = contribution;
    }
    {
      // inv_gamma_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_gamma_lpdf((1.3999999999999999 + 0.0625 * theta[40]) | (2 + 0.0625 * theta[41]), (1.3 + 0.0625 * theta[42]));
      values[21] = contribution;
    }
    {
      // lambert_wm1(real)=>real
      real contribution = 0;
      contribution += 1 * lambert_wm1((-0.20000000000000001 + 0.0625 * theta[43]));
      values[22] = contribution;
    }
    {
      // lmgamma(int,real)=>real
      real contribution = 0;
      contribution += 1 * lmgamma(2, (2 + 0.0625 * theta[44]));
      values[23] = contribution;
    }
    {
      // log1m_exp(real)=>real
      real contribution = 0;
      contribution += 1 * log1m_exp((-0.5 + 0.0625 * theta[45]));
      values[24] = contribution;
    }
    {
      // log_diff_exp(int,real)=>real
      real contribution = 0;
      contribution += 1 * log_diff_exp(2, (0.5 + 0.0625 * theta[46]));
      values[25] = contribution;
    }
    {
      // log_modified_bessel_first_kind(int,real)=>real
      real contribution = 0;
      contribution += 1 * log_modified_bessel_first_kind(2, (0.5 + 0.0625 * theta[47]));
      values[26] = contribution;
    }
    {
      // logistic_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * logistic_lcdf((0.40000000000000002 + 0.0625 * theta[48]) | (0.20000000000000001 + 0.0625 * theta[49]), (1.3 + 0.0625 * theta[50]));
      values[27] = contribution;
    }
    {
      // lognormal_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lognormal_cdf((1.3999999999999999 + 0.0625 * theta[51]) | (0.20000000000000001 + 0.0625 * theta[52]), (1.3 + 0.0625 * theta[53]));
      values[28] = contribution;
    }
    {
      // lower_bound_jacobian(real,real)=>real
      real contribution = 0;
      contribution += 1 * lower_bound_jacobian((0.5 + 0.0625 * theta[54]), (1.25 + 0.0625 * theta[55]));
      values[29] = contribution;
    }
    {
      // minus(real)=>real
      real contribution = 0;
      contribution += 1 * minus((0.5 + 0.0625 * theta[56]));
      values[30] = contribution;
    }
    {
      // neg_binomial_2_lccdf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_2_lccdf(3 | (2 + 0.0625 * theta[57]), (1.3 + 0.0625 * theta[58]));
      values[31] = contribution;
    }
    {
      // neg_binomial_lccdf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_lccdf(3 | (2 + 0.0625 * theta[59]), (1.3 + 0.0625 * theta[60]));
      values[32] = contribution;
    }
    {
      // normal_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * normal_lcdf((0.40000000000000002 + 0.0625 * theta[61]) | (0.20000000000000001 + 0.0625 * theta[62]), (1.3 + 0.0625 * theta[63]));
      values[33] = contribution;
    }
    {
      // owens_t(real,real)=>real
      real contribution = 0;
      contribution += 1 * owens_t((0.5 + 0.0625 * theta[64]), (1.25 + 0.0625 * theta[65]));
      values[34] = contribution;
    }
    {
      // pareto_type_2_cdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_type_2_cdf((1.3999999999999999 + 0.0625 * theta[66]) | (0 + 0.0625 * theta[67]), (1.2 + 0.0625 * theta[68]), (1.3 + 0.0625 * theta[69]));
      values[35] = contribution;
    }
    {
      // poisson_cdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * poisson_cdf(3 | (1.3 + 0.0625 * theta[70]));
      values[36] = contribution;
    }
    {
      // pow(int,real)=>real
      real contribution = 0;
      contribution += 1 * pow(2, (0.5 + 0.0625 * theta[71]));
      values[37] = contribution;
    }
    {
      // rising_factorial(real,int)=>real
      real contribution = 0;
      contribution += 1 * rising_factorial((1.5 + 0.0625 * theta[72]), 2);
      values[38] = contribution;
    }
    {
      // sin(real)=>real
      real contribution = 0;
      contribution += 1 * sin((0.5 + 0.0625 * theta[73]));
      values[39] = contribution;
    }
    {
      // skew_double_exponential_lpdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_double_exponential_lpdf((0.40000000000000002 + 0.0625 * theta[74]) | (0.20000000000000001 + 0.0625 * theta[75]), (1.3 + 0.0625 * theta[76]), (0.59999999999999998 + 0.0625 * theta[77]));
      values[40] = contribution;
    }
    {
      // sqrt(real)=>real
      real contribution = 0;
      contribution += 1 * sqrt((1.3999999999999999 + 0.0625 * theta[78]));
      values[41] = contribution;
    }
    {
      // std_normal_lcdf(real)=>real
      real contribution = 0;
      contribution += 1 * std_normal_lcdf((0.40000000000000002 + 0.0625 * theta[79]));
      values[42] = contribution;
    }
    {
      // student_t_lccdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * student_t_lccdf((0.40000000000000002 + 0.0625 * theta[80]) | (3 + 0.0625 * theta[81]), (0.20000000000000001 + 0.0625 * theta[82]), (1.3 + 0.0625 * theta[83]));
      values[43] = contribution;
    }
    {
      // tan(real)=>real
      real contribution = 0;
      contribution += 1 * tan((0.5 + 0.0625 * theta[84]));
      values[44] = contribution;
    }
    {
      // uniform_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * uniform_lccdf((0.40000000000000002 + 0.0625 * theta[85]) | (-1 + 0.0625 * theta[86]), (1.5 + 0.0625 * theta[87]));
      values[45] = contribution;
    }
    {
      // upper_bound_unconstrain(real,real)=>real
      real contribution = 0;
      contribution += 1 * upper_bound_unconstrain((0.5 + 0.0625 * theta[88]), (1.25 + 0.0625 * theta[89]));
      values[46] = contribution;
    }
    {
      // weibull_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * weibull_cdf((1.3999999999999999 + 0.0625 * theta[90]) | (2 + 0.0625 * theta[91]), (1.3 + 0.0625 * theta[92]));
      values[47] = contribution;
    }
    {
      // yule_simon_cdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * yule_simon_cdf(3 | (1.3 + 0.0625 * theta[93]));
      values[48] = contribution;
    }
    return values;
  }
}
parameters { vector[93] theta; }
transformed parameters {
  vector[48] observed = coverage_jacobian(theta);
}
model { target += sum(observed); }
