// Generated by tools/gen_function_models.py; do not edit.
functions {
  vector coverage_jacobian(vector theta) {
    vector[49] values;
    {
      // Phi_approx(real)=>real
      real contribution = 0;
      contribution += 1 * Phi_approx((0.5 + 0.0625 * theta[1]));
      values[1] = contribution;
    }
    {
      // asin(real)=>real
      real contribution = 0;
      contribution += 1 * asin((0.34999999999999998 + 0.0625 * theta[2]));
      values[2] = contribution;
    }
    {
      // bernoulli_cdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * bernoulli_cdf(0 | (0.40000000000000002 + 0.0625 * theta[3]));
      values[3] = contribution;
    }
    {
      // bessel_first_kind(int,real)=>real
      real contribution = 0;
      contribution += 1 * bessel_first_kind(2, (1.3999999999999999 + 0.0625 * theta[4]));
      values[4] = contribution;
    }
    {
      // beta_binomial_lcdf(int,int,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_binomial_lcdf(3 | 10, (2 + 0.0625 * theta[5]), (3 + 0.0625 * theta[6]));
      values[5] = contribution;
    }
    {
      // beta_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * beta_lpdf((0.40000000000000002 + 0.0625 * theta[7]) | (2 + 0.0625 * theta[8]), (1.3 + 0.0625 * theta[9]));
      values[6] = contribution;
    }
    {
      // beta_proportion_lccdf(real,real,int)=>real
      real contribution = 0;
      contribution += 1 * beta_proportion_lccdf((0.40000000000000002 + 0.0625 * theta[10]) | (0.59999999999999998 + 0.0625 * theta[11]), 2);
      values[7] = contribution;
    }
    {
      // binomial_lccdf(int,int,real)=>real
      real contribution = 0;
      contribution += 1 * binomial_lccdf(3 | 10, (0.40000000000000002 + 0.0625 * theta[12]));
      values[8] = contribution;
    }
    {
      // cauchy_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * cauchy_lccdf((0.40000000000000002 + 0.0625 * theta[13]) | (0.20000000000000001 + 0.0625 * theta[14]), (1.3 + 0.0625 * theta[15]));
      values[9] = contribution;
    }
    {
      // chi_square_lccdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * chi_square_lccdf((1.3999999999999999 + 0.0625 * theta[16]) | (3 + 0.0625 * theta[17]));
      values[10] = contribution;
    }
    {
      // digamma(real)=>real
      real contribution = 0;
      contribution += 1 * digamma((1.3999999999999999 + 0.0625 * theta[18]));
      values[11] = contribution;
    }
    {
      // double_exponential_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * double_exponential_lpdf((0.40000000000000002 + 0.0625 * theta[19]) | (0.20000000000000001 + 0.0625 * theta[20]), (1.3 + 0.0625 * theta[21]));
      values[12] = contribution;
    }
    {
      // exp(real)=>real
      real contribution = 0;
      contribution += 1 * exp((0.5 + 0.0625 * theta[22]));
      values[13] = contribution;
    }
    {
      // exp_mod_normal_lpdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * exp_mod_normal_lpdf((0.40000000000000002 + 0.0625 * theta[23]) | (0.20000000000000001 + 0.0625 * theta[24]), (1.3 + 0.0625 * theta[25]), (0.69999999999999996 + 0.0625 * theta[26]));
      values[14] = contribution;
    }
    {
      // exponential_lpdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * exponential_lpdf((1.3999999999999999 + 0.0625 * theta[27]) | (0.69999999999999996 + 0.0625 * theta[28]));
      values[15] = contribution;
    }
    {
      // fmin(int,real)=>real
      real contribution = 0;
      contribution += 1 * fmin(2, (2 + 0.0625 * theta[29]));
      values[16] = contribution;
    }
    {
      // frechet_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * frechet_lpdf((1.3999999999999999 + 0.0625 * theta[30]) | (2 + 0.0625 * theta[31]), (1.3 + 0.0625 * theta[32]));
      values[17] = contribution;
    }
    {
      // gamma_p(real,real)=>real
      real contribution = 0;
      contribution += 1 * gamma_p((2 + 0.0625 * theta[33]), (1.3 + 0.0625 * theta[34]));
      values[18] = contribution;
    }
    {
      // gumbel_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * gumbel_lpdf((0.40000000000000002 + 0.0625 * theta[35]) | (0.20000000000000001 + 0.0625 * theta[36]), (1.3 + 0.0625 * theta[37]));
      values[19] = contribution;
    }
    {
      // inv_chi_square_lccdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_chi_square_lccdf((1.3999999999999999 + 0.0625 * theta[38]) | (3 + 0.0625 * theta[39]));
      values[20] = contribution;
    }
    {
      // inv_gamma_cdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * inv_gamma_cdf((1.3999999999999999 + 0.0625 * theta[40]) | (2 + 0.0625 * theta[41]), (1.3 + 0.0625 * theta[42]));
      values[21] = contribution;
    }
    {
      // inv_sqrt(real)=>real
      real contribution = 0;
      contribution += 1 * inv_sqrt((1.3999999999999999 + 0.0625 * theta[43]));
      values[22] = contribution;
    }
    {
      // lchoose(int,real)=>real
      real contribution = 0;
      contribution += 1 * lchoose(4, (2 + 0.0625 * theta[44]));
      values[23] = contribution;
    }
    {
      // log(real)=>real
      real contribution = 0;
      contribution += 1 * log((1.3999999999999999 + 0.0625 * theta[45]));
      values[24] = contribution;
    }
    {
      // log1p(real)=>real
      real contribution = 0;
      contribution += 1 * log1p((0.5 + 0.0625 * theta[46]));
      values[25] = contribution;
    }
    {
      // log_inv_logit(real)=>real
      real contribution = 0;
      contribution += 1 * log_inv_logit((0.5 + 0.0625 * theta[47]));
      values[26] = contribution;
    }
    {
      // log_sum_exp(int,real)=>real
      real contribution = 0;
      contribution += 1 * log_sum_exp(2, (0.5 + 0.0625 * theta[48]));
      values[27] = contribution;
    }
    {
      // logit(real)=>real
      real contribution = 0;
      contribution += 1 * logit((0.34999999999999998 + 0.0625 * theta[49]));
      values[28] = contribution;
    }
    {
      // lognormal_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lognormal_lcdf((1.3999999999999999 + 0.0625 * theta[50]) | (0.20000000000000001 + 0.0625 * theta[51]), (1.3 + 0.0625 * theta[52]));
      values[29] = contribution;
    }
    {
      // lower_upper_bound_constrain(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * lower_upper_bound_constrain((0 + 0.0625 * theta[53]), (-1 + 0.0625 * theta[54]), (1 + 0.0625 * theta[55]));
      values[30] = contribution;
    }
    {
      // modified_bessel_second_kind(int,real)=>real
      real contribution = 0;
      contribution += 1 * modified_bessel_second_kind(2, (1.3999999999999999 + 0.0625 * theta[56]));
      values[31] = contribution;
    }
    {
      // neg_binomial_2_log_lpmf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_2_log_lpmf(3 | (0.40000000000000002 + 0.0625 * theta[57]), (1.3 + 0.0625 * theta[58]));
      values[32] = contribution;
    }
    {
      // neg_binomial_lpmf(int,real,real)=>real
      real contribution = 0;
      contribution += 1 * neg_binomial_lpmf(3 | (2 + 0.0625 * theta[59]), (1.3 + 0.0625 * theta[60]));
      values[33] = contribution;
    }
    {
      // offset_multiplier_constrain(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * offset_multiplier_constrain((0.5 + 0.0625 * theta[61]), (1.25 + 0.0625 * theta[62]), (0.75 + 0.0625 * theta[63]));
      values[34] = contribution;
    }
    {
      // pareto_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_lccdf((2.3999999999999999 + 0.0625 * theta[64]) | (1 + 0.0625 * theta[65]), (1.3 + 0.0625 * theta[66]));
      values[35] = contribution;
    }
    {
      // pareto_type_2_lcdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * pareto_type_2_lcdf((1.3999999999999999 + 0.0625 * theta[67]) | (0 + 0.0625 * theta[68]), (1.2 + 0.0625 * theta[69]), (1.3 + 0.0625 * theta[70]));
      values[36] = contribution;
    }
    {
      // poisson_lcdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * poisson_lcdf(3 | (1.3 + 0.0625 * theta[71]));
      values[37] = contribution;
    }
    {
      // rayleigh_lccdf(real,real)=>real
      real contribution = 0;
      contribution += 1 * rayleigh_lccdf((1.3999999999999999 + 0.0625 * theta[72]) | (1.3 + 0.0625 * theta[73]));
      values[38] = contribution;
    }
    {
      // scaled_inv_chi_square_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * scaled_inv_chi_square_lccdf((1.3999999999999999 + 0.0625 * theta[74]) | (3 + 0.0625 * theta[75]), (1.2 + 0.0625 * theta[76]));
      values[39] = contribution;
    }
    {
      // skew_double_exponential_cdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_double_exponential_cdf((0.40000000000000002 + 0.0625 * theta[77]) | (0.20000000000000001 + 0.0625 * theta[78]), (1.3 + 0.0625 * theta[79]), (0.59999999999999998 + 0.0625 * theta[80]));
      values[40] = contribution;
    }
    {
      // skew_normal_lccdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * skew_normal_lccdf((0.40000000000000002 + 0.0625 * theta[81]) | (0.20000000000000001 + 0.0625 * theta[82]), (1.3 + 0.0625 * theta[83]), (0.69999999999999996 + 0.0625 * theta[84]));
      values[41] = contribution;
    }
    {
      // squared_distance(real,real)=>real
      real contribution = 0;
      contribution += 1 * squared_distance((0.5 + 0.0625 * theta[85]), (1.25 + 0.0625 * theta[86]));
      values[42] = contribution;
    }
    {
      // std_normal_lpdf(real)=>real
      real contribution = 0;
      contribution += 1 * std_normal_lpdf((0.40000000000000002 + 0.0625 * theta[87]));
      values[43] = contribution;
    }
    {
      // student_t_lpdf(real,real,real,real)=>real
      real contribution = 0;
      contribution += 1 * student_t_lpdf((0.40000000000000002 + 0.0625 * theta[88]) | (3 + 0.0625 * theta[89]), (0.20000000000000001 + 0.0625 * theta[90]), (1.3 + 0.0625 * theta[91]));
      values[44] = contribution;
    }
    {
      // tgamma(real)=>real
      real contribution = 0;
      contribution += 1 * tgamma((0.5 + 0.0625 * theta[92]));
      values[45] = contribution;
    }
    {
      // uniform_lpdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * uniform_lpdf((0.40000000000000002 + 0.0625 * theta[93]) | (-1 + 0.0625 * theta[94]), (1.5 + 0.0625 * theta[95]));
      values[46] = contribution;
    }
    {
      // von_mises_lccdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * von_mises_lccdf((0.40000000000000002 + 0.0625 * theta[96]) | (0.20000000000000001 + 0.0625 * theta[97]), (1.3 + 0.0625 * theta[98]));
      values[47] = contribution;
    }
    {
      // weibull_lcdf(real,real,real)=>real
      real contribution = 0;
      contribution += 1 * weibull_lcdf((1.3999999999999999 + 0.0625 * theta[99]) | (2 + 0.0625 * theta[100]), (1.3 + 0.0625 * theta[101]));
      values[48] = contribution;
    }
    {
      // yule_simon_lcdf(int,real)=>real
      real contribution = 0;
      contribution += 1 * yule_simon_lcdf(3 | (1.3 + 0.0625 * theta[102]));
      values[49] = contribution;
    }
    return values;
  }
}
parameters { vector[102] theta; }
transformed parameters {
  vector[49] observed = coverage_jacobian(theta);
}
model { target += sum(observed); }
