#!/usr/bin/env bash
# Build the release wheel: optimized shared library, stripped, plus license
# notices. Release builds come from build-rel so a debug library can never
# ship by accident, and the platform tag names the architecture the library
# was actually built for (the default tag on macOS claims universal2, which
# would let the wheel install on machines it cannot run on).
set -euo pipefail
cd "$(dirname "$0")/.."

cmake --build build-rel -j8 --target stanli_shared

mkdir -p python/stanli/_bin
rm -f python/stanli/_bin/*
LIB=""
for cand in build-rel/libstanli.dylib build-rel/libstanli.so \
            build-rel/stanli.dll; do
  [ -f "$cand" ] && LIB=$cand && break
done
[ -n "$LIB" ] || { echo "no shared library in build-rel/"; exit 1; }
cp "$LIB" python/stanli/_bin/
# Attribute the size before stripping: the shipped library exports a few
# hundred C ABI names and carries no static symbol table, so this is the
# only moment the breakdown in docs/binary-size.md can be measured at all.
# Best effort -- a toolchain whose nm cannot report symbol sizes (Apple's
# cannot, for Mach-O) leaves the last good file in place rather than
# failing the wheel.
if python3 tools/binary_size.py "$LIB" > /tmp/binary-size.$$ 2>/dev/null; then
  { echo "<!-- Generated by tools/binary_size.py; do not edit. -->"
    echo "# Binary size"
    echo
    cat /tmp/binary-size.$$; } > docs/binary-size.md
fi
rm -f /tmp/binary-size.$$
strip -x "python/stanli/_bin/$(basename "$LIB")" 2>/dev/null || true
cp THIRD_PARTY_LICENSES.md LICENSE python/stanli/

# Without the embedded compiler the package needs the stanc binary instead.
if [ ! -f deps/stanc3/stanc_embed.o ]; then
  case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) cp deps/stanc3/stanc python/stanli/_bin/stanc.exe ;;
    *) cp deps/stanc3/stanc python/stanli/_bin/stanc
       chmod +x python/stanli/_bin/stanc ;;
  esac
fi

case "$(uname -s)-$(uname -m)" in
  Darwin-arm64) PLAT=macosx_11_0_arm64 ;;
  Darwin-x86_64) PLAT=macosx_10_15_x86_64 ;;
  Linux-aarch64) PLAT=manylinux_2_28_aarch64 ;;
  Linux-x86_64) PLAT=manylinux_2_28_x86_64 ;;
  MINGW*|MSYS*|CYGWIN*) PLAT=win_amd64 ;;
  *) echo "unknown platform: $(uname -s)-$(uname -m)"; exit 1 ;;
esac

rm -rf dist build/lib build/bdist.* python/build python/*.egg-info
(cd python && python3 setup.py -q bdist_wheel --plat-name "$PLAT" \
    --dist-dir ../dist)
rm -rf python/build python/*.egg-info
ls -la dist/
