#!/usr/bin/env python3
"""Generate ten integrated function-coverage models and their name manifest.

Select one small, previously verified signature per function name from the
exhaustive inventory, then add explicit recipes for container, data-only,
multivariate, RNG and higher-order calls. This is name coverage, not overload
coverage. Regeneration is deterministic and --check never changes files.
"""
from __future__ import annotations

import argparse
import gzip
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "harnesses"))
sys.path.insert(0, str(REPO / "tests" / "function_coverage"))
from conformance.generate import generated_inventory
from conformance.signatures import inventory_from_dump
from recipes import GROUPS, HELPERS, PREAMBLE

DEST = REPO / "tests" / "function_coverage"


def render():
    baseline = json.loads(gzip.decompress(
        (REPO / "docs/conformance-baseline.json.gz").read_bytes()))
    rows = baseline["classifications"]
    # Canonical IDs use the same grammar as stanc's signature dump. These
    # checked-in signatures and classifications are the selection authority;
    # no compiler executable is needed for the fast freshness gate.
    inventory = inventory_from_dump(
        "\n".join(k for k in rows if not k.startswith("construct:")),
        "checked-in conformance baseline")
    signatures = inventory.signatures
    candidates = {}
    for spec in generated_inventory(inventory):
        if rows.get(spec.inventory_id, {}).get("status") != "verified":
            continue
        candidates.setdefault(spec.signature.name, []).append(spec)
    specs = [min(v, key=lambda s: (s.parameter_count, len(s.inventory_id),
                                    s.inventory_id))
             for _, v in sorted(candidates.items())]
    outputs, manifest = {}, {"schema": 1, "models": {}}
    for group in range(5):
        chunk = specs[group::5]
        width = sum(s.parameter_count for s in chunk)
        body, offset = [], 0
        for i, spec in enumerate(chunk, 1):
            body += ["    {", f"      // {spec.inventory_id}",
                     "      real contribution = 0;"]
            body += ["      " + line for line in spec.render_body(offset, 1.0)]
            body += [f"      values[{i}] = contribution;", "    }"]
            offset += spec.parameter_count
        name = f"scalar_{group + 1}"
        outputs[name + ".stan"] = (
            "// Generated by tools/gen_function_models.py; do not edit.\n"
            "functions {\n"
            "  vector coverage_jacobian(vector theta) {\n"
            f"    vector[{len(chunk)}] values;\n" + "\n".join(body) +
            "\n    return values;\n  }\n}\n"
            f"parameters {{ vector[{width}] theta; }}\n"
            "transformed parameters {\n"
            f"  vector[{len(chunk)}] observed = coverage_jacobian(theta);\n"
            "}\nmodel { target += sum(observed); }\n")
        manifest["models"][name] = {
            "names": [s.signature.name for s in chunk],
            "signatures": [s.inventory_id for s in chunk],
            "parameters": width,
        }

    for group, recipes in GROUPS.items():
        declarations = [f"  observed[{i}] = probe({expr}); // {name}"
                        for i, (name, expr) in enumerate(recipes.items(), 1)]
        name = group
        header = "// Generated by tools/gen_function_models.py; do not edit.\n"
        source = header + "functions {\n" + HELPERS + "}\n"
        if group == "data_functions":
            source += "transformed data {\n" + PREAMBLE["data_functions"]
            source += f"  vector[{len(recipes)}] observed;\n"
            source += "\n".join(declarations) + "\n}\n"
            source += "parameters { real theta; }\n"
            source += "model { target += (1 + theta) * sum(observed); }\n"
            source += f"generated quantities {{ vector[{len(recipes)}] values = observed; }}\n"
        else:
            if group == "multivariate":
                source += ("transformed data {\n"
                           "  array[2] int binary = {0,1};\n"
                           "  array[2] int count = {1,2};\n"
                           "  array[2] int trials = {3,4};\n"
                           "  matrix[2,2] design = [[1,0.3],[0.2,1.5]];\n}\n")
            source += "parameters { vector[8] theta; }\n"
            if group == "rng_functions":
                source += "model { target += dot_self(theta); }\n"
                source += "generated quantities {\n" + PREAMBLE[group]
            else:
                source += "transformed parameters {\n" + PREAMBLE[group]
            source += f"  vector[{len(recipes)}] observed;\n"
            source += "\n".join(declarations) + "\n}\n"
            if group != "rng_functions":
                source += "model { target += sum(observed); }\n"
        outputs[name + ".stan"] = source
        manifest["models"][name] = {"names": list(recipes),
                                     "parameters": 1 if group == "data_functions" else 8}

    higher = DEST / "higher_order.stan"
    higher_names = sorted(set(re.findall(
        r"\b((?:ode_\w+|integrate_ode_\w+|integrate_1d|algebra_solver|map_rect|reduce_sum(?:_static)?))\s*\(",
        higher.read_text())))
    # These entry points share the same callback signature and lowering/kernel
    # family.  The family probe covers the common ABI; focused lowering tests
    # exercise the solver selection independently.
    higher_aliases = {"algebra_solver": {"algebra_solver_newton"}}
    higher_names = sorted(set(higher_names).union(*(
        aliases for base, aliases in higher_aliases.items()
        if base in higher_names)))
    manifest["models"]["higher_order"] = {"names": higher_names, "parameters": 2}
    covered = {n for m in manifest["models"].values() for n in m["names"]}
    # Literal dispatch names and X-macro registrations must acquire a probe
    # when a new function is wired up. A mention is not proof of support,
    # hence the explicit, reviewed refusals below.
    inventory_names = {s.name for s in signatures}
    runtime = "\n".join(p.read_text() for base in
                        (REPO / "runtime/src", REPO / "runtime/include/stanli")
                        for p in sorted(base.iterdir())
                        if p.suffix in (".cpp", ".hpp"))
    literals = set(re.findall(r'"([A-Za-z][A-Za-z0-9_]+)"', runtime))
    macros = set(re.findall(r"X\(OP_[A-Z_0-9]+,\s*([A-Za-z_0-9]+),", runtime))
    candidates = inventory_names & (literals | macros)
    refusals = {
        "gaussian_dlm_obs_lpdf": "Explicitly refused: seven inputs exceed the graph's six-input operation layout.",
    }
    focused = {
        name: "tests/fixtures/quadrature_region.stan exercises graph and runtime-control lowering"
        for name in (
            "integrate_1d",
            "integrate_1d_double_exponential",
            "integrate_1d_double_exponential_tol",
            "integrate_1d_gauss_kronrod",
            "integrate_1d_gauss_kronrod_tol",
        )
    }
    focused["integrate_ode"] = (
        "tests/fixtures/higher_order_all_contexts.stan exercises transformed-data, "
        "graph, runtime-control, and interpreted write_array execution"
    )
    for name in ("ones_int_array", "zeros_array", "one_hot_vector",
                 "one_hot_row_vector", "one_hot_array", "one_hot_int_array",
                 "uniform_simplex"):
        focused[name] = (
            "generated tests/fixtures/builtin_signatures fixtures execute "
            "every registered constructor overload in transformed data, "
            "graph, runtime-control, and generated-quantities contexts"
        )
    missing = candidates - covered - set(refusals) - set(focused)
    if missing:
        raise ValueError("Runtime functions need coverage recipes: " + ", ".join(sorted(missing)))
    manifest["recognized_but_unsupported"] = refusals
    manifest["focused_coverage"] = focused
    manifest["scope"] = {
        "overloads": "At least one supported signature per name, not every overload.",
        "gp covariance": "Coordinates are data; scale and length-scale are active.",
        "map_rect": (
            "The integrated probe covers empty jobs; "
            "tests/fixtures/map_rect_region.stan covers nonempty serial "
            "graph and runtime-control lowering."
        ),
        "predicates": "logical_negation also exercises a parameter-dependent region.",
    }
    manifest["covered_names"] = sorted(covered)
    manifest["name_count"] = len(covered)
    outputs["manifest.json"] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, contents in render().items():
        path = DEST / name
        if args.check:
            if not path.exists() or path.read_text() != contents:
                stale.append(str(path.relative_to(REPO)))
        else:
            path.write_text(contents)
    if stale:
        raise SystemExit("Regenerate with tools/gen_function_models.py: " + ", ".join(stale))


if __name__ == "__main__":
    main()
