# Experimental, allocator-independent mitigation for a measured code-layout
# cliff on Apple silicon. No Stan Math/Eigen source or validation changes.
# Keep OFF until the broad consumer/corpus gate has justified promotion.
set(STANLI_ALIGN_LOOPS "OFF" CACHE STRING "Native loop alignment: AUTO, ON, or OFF")
set_property(CACHE STANLI_ALIGN_LOOPS PROPERTY STRINGS AUTO ON OFF)
if(NOT STANLI_ALIGN_LOOPS MATCHES "^(AUTO|ON|OFF)$")
  message(FATAL_ERROR "STANLI_ALIGN_LOOPS must be AUTO, ON, or OFF")
endif()
set(STANLI_USE_LOOP_ALIGNMENT OFF)

function(stanli_loop_alignment_supported result)
  set(_arch "${CMAKE_OSX_ARCHITECTURES}")
  if(NOT _arch)
    set(_arch "${CMAKE_SYSTEM_PROCESSOR}")
  endif()
  set(_supported OFF)
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND _arch STREQUAL "arm64" AND
     CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang" AND NOT EMSCRIPTEN)
    set(_supported ON)
  endif()
  set(${result} ${_supported} PARENT_SCOPE)
endfunction()

function(stanli_apply_loop_alignment target)
  if(STANLI_ALIGN_LOOPS STREQUAL "OFF")
    return()
  endif()
  stanli_loop_alignment_supported(_supported)
  if(NOT _supported)
    if(STANLI_ALIGN_LOOPS STREQUAL "AUTO")
      return()
    endif()
    message(FATAL_ERROR
      "STANLI_ALIGN_LOOPS currently requires native macOS arm64 Apple Clang; use OFF")
  endif()
  include(CheckCXXCompilerFlag)
  check_cxx_compiler_flag("-falign-loops=32" STANLI_HAS_ALIGN_LOOPS_32)
  if(NOT STANLI_HAS_ALIGN_LOOPS_32)
    if(STANLI_ALIGN_LOOPS STREQUAL "AUTO")
      message(STATUS "Stanli loop alignment: compiler flag unavailable; retaining default layout")
      return()
    endif()
    message(FATAL_ERROR "Compiler does not support -falign-loops=32; use STANLI_ALIGN_LOOPS=OFF")
  endif()
  target_compile_options(${target} INTERFACE
    "$<$<OR:$<CONFIG:Release>,$<CONFIG:RelWithDebInfo>>:-falign-loops=32>")
  set(STANLI_USE_LOOP_ALIGNMENT ON PARENT_SCOPE)
  message(STATUS "Stanli experimental loop alignment: 32 bytes (Release/RelWithDebInfo)")
endfunction()
